### ISSUE TITLE
Todo items for migration

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/sandbox-wp-db#14]
When we're ready to deploy this sandbox code to the main repos, refer to this checklist:

- [ ] copy .github/workflows to `wikipathways-database`
- [ ] copy assests/main.scss, layouts/author.page, layouts/draft-pathway.page, browse/pending to `wikipathways.github.io`
- [ ] lock main branch to prevent PR merge: Settings/Branch/Add Rule: Lock branch

**Comment by ayushi-agrawal-gladstone** [comment]
- [ ] Provide admin access to subset of long term devs for code changes
