### ISSUE TITLE
Suggested updates to Reviewer Checklist  for "new pathway submission" PRs

### ISSUE THREAD

**Issue by khanspers** [wikipathways/sandbox-wp-db#27]
Below are some suggestions for updates to the **Reviewer Checklist** for "new pathway submission" PRs. 

- This assumes that it's possible to have different check lists for "new" and "updated" PRs
- The proposed new language for each item in the checklist is in the style of a task. I'm not sure if this is helpful, open to feedback.
- Reviewers can refer to the **Automated Testing** section to see results of automated tests, and maybe also some output from specific tests? For example, for the data node annotation test can we include a list of data nodes (node labels) with failed database lookup? 
- Some items reference tests that don't exist yet, so I made up numbers.

### Reviewer Checklist 
- [ ] Review the pathway title for relevance to the pathway content.
- [ ] Review the description for relevance to the pathway content, completeness and grammar.
- [ ] Review data node annotations: see incomplete node annotations under **Automated Testing**, test 5 results.
- [ ] Review interactions: see unconnected interactions under **Automated Testing**, test 6 results.
- [ ] Review source references for relevance.
- [ ] Review ontology terms for relevance.
- [ ] Review pathway diagram layout and style.
